#spring.application.name=apiPrueba
spring:
  application:
    name: apiPrueba
  jpa:
    database: POSTGRESQL
    show-sql: true # Mostrar sentencias Sql en la consola
    #show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    platform: postgres
#    url: jdbc:postgresql://localhost:5432/fcs_api
#    username: admin
#    password: postgresql
    url: jdbc:postgresql://localhost:5432/fcs_api
    username: postgres
    password: postgre123

    driverClassName: org.postgresql.Driver
#server:
#  port: 5432
server:
  error:
    include-message: always

#logging:
#  level:
#    org:
#      hibernate:
#         SQL: DEBUG
#      type:
#        descriptor:
#        sql:
#          BasicBinder: TRACE